// Códigos dos principais bancos brasileiros (COMPE).
// Não pretende ser exaustivo — caso o código não esteja aqui, mostramos apenas
// o número e um aviso amigável.
export const BANK_NAMES: Record<string, string> = {
  "001": "Banco do Brasil",
  "003": "Banco da Amazônia",
  "004": "Banco do Nordeste",
  "021": "Banestes",
  "025": "Banco Alfa",
  "027": "Besc",
  "029": "Banco Itaú Consignado",
  "033": "Santander",
  "037": "Banpará",
  "041": "Banrisul",
  "047": "Banco do Estado de Sergipe",
  "070": "BRB - Banco de Brasília",
  "077": "Banco Inter",
  "082": "Banco Topázio",
  "084": "Uniprime Norte do Paraná",
  "085": "Cooperativa Central de Crédito Ailos",
  "097": "Credisis",
  "099": "UNIPRIME Central",
  "104": "Caixa Econômica Federal",
  "121": "Agibank",
  "133": "Cresol",
  "136": "Unicred",
  "151": "Nossa Caixa",
  "184": "Itaú BBA",
  "208": "Banco BTG Pactual",
  "212": "Banco Original",
  "218": "Banco BS2",
  "224": "Banco Fibra",
  "237": "Bradesco",
  "246": "Banco ABC Brasil",
  "260": "Nubank",
  "265": "Banco Fator",
  "290": "PagBank (PagSeguro)",
  "323": "Mercado Pago",
  "335": "Banco Digio",
  "336": "Banco C6",
  "341": "Itaú Unibanco",
  "356": "Banco Real (extinto)",
  "364": "Gerencianet (Efí)",
  "380": "PicPay",
  "389": "Banco Mercantil do Brasil",
  "399": "HSBC (extinto)",
  "422": "Banco Safra",
  "453": "Banco Rural",
  "456": "Banco MUFG Brasil",
  "464": "Banco Sumitomo Mitsui",
  "473": "Banco Caixa Geral",
  "477": "Citibank",
  "479": "Banco ItauBank",
  "487": "Deutsche Bank",
  "488": "JPMorgan",
  "492": "ING Bank",
  "505": "Credit Suisse",
  "604": "Banco Industrial",
  "610": "Banco VR",
  "611": "Banco Paulista",
  "612": "Banco Guanabara",
  "613": "Omni Banco",
  "623": "Banco Pan",
  "626": "Banco Ficsa",
  "630": "Banco Smartbank",
  "633": "Banco Rendimento",
  "634": "Banco Triângulo",
  "637": "Banco Sofisa",
  "643": "Banco Pine",
  "652": "Itaú Unibanco Holding",
  "653": "Banco Indusval",
  "655": "Banco Votorantim",
  "707": "Banco Daycoval",
  "735": "Banco Neon",
  "739": "Banco Cetelem",
  "741": "Banco Ribeirão Preto",
  "743": "Banco Semear",
  "745": "Banco Citibank",
  "746": "Banco Modal",
  "748": "Sicredi",
  "751": "Scotiabank",
  "752": "BNP Paribas Brasil",
  "755": "Bank of America Merrill Lynch",
  "756": "Sicoob",
  "757": "Banco KEB Hana",
};

export function bankName(code: string): string {
  return BANK_NAMES[code] ?? `Banco ${code}`;
}
