// Vincula o usuário autenticado a um chat do Telegram (despesas ou relatórios)
// a partir de um bot_code curto digitado no app. O bot_code é gerado pelo
// próprio bot (comando /code) e gravado em public.telegram_bots.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return json({ error: "Unauthorized" }, 401);

    const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    const token = authHeader.replace(/^Bearer\s+/i, "");
    const { data: claimsData, error: claimsErr } = await userClient.auth.getClaims(token);
    const userId = claimsData?.claims?.sub as string | undefined;
    if (claimsErr || !userId) return json({ error: "Unauthorized" }, 401);

    let body: any = {};
    try { body = await req.json(); } catch { body = {}; }

    const rawCode = typeof body?.bot_code === "string" ? body.bot_code : "";
    const code = rawCode.trim().toUpperCase().replace(/[^A-Z0-9]/g, "");
    if (!code || code.length < 4 || code.length > 12) {
      return json({ error: "Código inválido. Informe o bot_code recebido no Telegram." }, 400);
    }

    const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // 1) Try standard alphanumeric code from public.telegram_bots (generated by /code in bot)
    const { data: bot, error: botErr } = await admin
      .from("telegram_bots")
      .select("id, bot_code, kind, chat_id, bot_id, expires_at")
      .eq("bot_code", code)
      .maybeSingle();

    if (botErr) return json({ error: botErr.message }, 500);

    if (bot) {
      if ((bot as any).expires_at && new Date((bot as any).expires_at).getTime() < Date.now()) {
        return json({ error: "Código expirado. Gere um novo no bot enviando /code." }, 410);
      }
    } else {
      // 2) Fallback: check 6-digit numeric code from public.telegram_link_codes (generated by app)
      const { data: linkCode, error: lcErr } = await admin
        .from("telegram_link_codes")
        .select("id, code, user_id, expires_at")
        .eq("code", code)
        .maybeSingle();

      if (lcErr) return json({ error: lcErr.message }, 500);

      if (linkCode) {
        // Validation: linkCode user must be the current user
        if (linkCode.user_id !== userId) {
          return json({ error: "Código pertence a outro usuário." }, 403);
        }
        if (new Date(linkCode.expires_at).getTime() < Date.now()) {
          return json({ error: "Código expirado no app." }, 410);
        }
        // In link-by-code (reverse), we don't have the chat_id yet.
        // This edge function is called from the APP with a code.
        // If it's a numeric code from the app, it means the user is typing a code
        // that SHOULD have been sent from the BOT.
        // But /start 123456 is what the user does in the bot.
        // If the user is typing in the APP, they should be typing a code shown by the BOT.
        return json({ error: "Código de bot inválido. Certifique-se de que está usando o código gerado pelo BOT (comando /code)." }, 404);
      }

      return json({ error: "Código de bot inválido" }, 404);
    }


    if ((bot as any).expires_at && new Date((bot as any).expires_at).getTime() < Date.now()) {
      return json({ error: "Código expirado. Gere um novo no bot enviando /code." }, 410);
    }

    const kind = (bot as any).kind as "expenses" | "reports";
    const chatId = Number((bot as any).chat_id);

    const targetTable = kind === "reports" ? "telegram_reports_links" : "telegram_links";
    const rawLabel = typeof body?.label === "string" ? body.label.trim().slice(0, 80) : "";
    const label = rawLabel || null;

    // Múltiplos vínculos paralelos: chave = (user_id, chat_id).
    // Se já existir, atualiza bot_code/label preservando dados; senão cria novo
    // sem remover outros vínculos existentes do mesmo usuário.
    const { error: upsertErr } = await admin
      .from(targetTable)
      .upsert(
        { user_id: userId, chat_id: chatId, bot_id: (bot as any).bot_id ?? null, bot_code: code, label },
        { onConflict: "user_id,chat_id" },
      );

    if (upsertErr) return json({ error: upsertErr.message }, 500);

    // One-shot: invalida o código consumido (o vínculo persiste em telegram_*_links
    // e pode ser reutilizado por outros relatórios sem refazer o pareamento).
    await admin.from("telegram_bots").delete().eq("id", (bot as any).id);

    return json({
      ok: true,
      kind,
      chat_id: chatId,
      bot_code: code,
      label,
      message: "Bot vinculado com sucesso. O código foi consumido, mas o vínculo permanece salvo.",
    });
  } catch (e: any) {
    return json({ error: e?.message ?? "Erro interno" }, 500);
  }
});
