// Vincula o usuário autenticado a um chat do Telegram (despesas ou relatórios)
// a partir de um bot_code curto digitado no app. O bot_code é gerado pelo
// próprio bot (comando /code) e gravado em public.telegram_bots.
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function normalizeBotCode(value: unknown) {
  return String(value ?? "")
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]/g, "");
}

function getCodeCandidates(code: string) {
  const chars = code.split("");
  const variants = new Set<string>([code]);
  const swaps: Record<string, string[]> = {
    O: ["0"],
    0: ["O"],
    I: ["1", "L"],
    L: ["1", "I"],
    1: ["I", "L"],
    S: ["5"],
    5: ["S"],
    B: ["8"],
    8: ["B"],
  };

  chars.forEach((char, index) => {
    for (const replacement of swaps[char] ?? []) {
      const next = [...chars];
      next[index] = replacement;
      variants.add(next.join(""));
    }
  });

  return [...variants].slice(0, 20);
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY")!;
    const SUPABASE_SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

    const authHeader = req.headers.get("Authorization");
    if (!authHeader) return json({ error: "Unauthorized" }, 401);

    const userClient = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
    const token = authHeader.replace(/^Bearer\s+/i, "");
    const { data: { user }, error: userErr } = await userClient.auth.getUser(token);
    const userId = user?.id;
    if (userErr || !userId) return json({ error: "Unauthorized" }, 401);

    let body: any = {};
    try { body = await req.json(); } catch { body = {}; }

    const code = normalizeBotCode(body?.bot_code ?? body?.code);
    if (!code || code.length < 4 || code.length > 12) {
      return json({ error: "Código inválido. Informe o bot_code recebido no Telegram." }, 400);
    }

    const codeCandidates = getCodeCandidates(code);

    const admin = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

    // 1) Try standard alphanumeric code from public.telegram_bots (generated by /code in bot)
    const { data: botRows, error: botErr } = await admin
      .from("telegram_bots")
      .select("id, bot_code, kind, chat_id, bot_id, expires_at")
      .in("bot_code", codeCandidates)
      .order("created_at", { ascending: false })
      .limit(1);

    if (botErr) return json({ error: botErr.message }, 500);
    const bot = Array.isArray(botRows) && botRows.length > 0 ? botRows[0] : null;

    if (bot) {
      if ((bot as any).expires_at && new Date((bot as any).expires_at).getTime() < Date.now()) {
        return json({ error: "Código expirado. Gere um novo no bot enviando /code." }, 410);
      }
    } else {
      // 2) Check 6-digit numeric code from public.telegram_link_codes (expenses)
      const { data: expCode, error: expErr } = await admin
        .from("telegram_link_codes")
        .select("id, code, user_id, expires_at")
        .eq("code", code)
        .maybeSingle();

      if (expErr) return json({ error: expErr.message }, 500);

      if (expCode) {
        if (expCode.user_id !== userId) return json({ error: "Código pertence a outro usuário." }, 403);
        if (new Date(expCode.expires_at).getTime() < Date.now()) return json({ error: "Código expirado no app." }, 410);

        return json({
          error: "Para vincular este bot, você deve enviar o comando no Telegram. Copie o comando: /start " + code
        }, 400);
      }

      // 3) Check 6-digit numeric code from public.telegram_reports_link_codes (reports)
      const { data: repCode, error: repErr } = await admin
        .from("telegram_reports_link_codes")
        .select("id, code, user_id, expires_at")
        .eq("code", code)
        .maybeSingle();

      if (repErr) return json({ error: repErr.message }, 500);

      if (repCode) {
        if (repCode.user_id !== userId) return json({ error: "Código pertence a outro usuário." }, 403);
        if (new Date(repCode.expires_at).getTime() < Date.now()) return json({ error: "Código expirado no app." }, 410);

        return json({
          error: "Para vincular este bot, você deve enviar o comando no Telegram. Copie o comando: /start " + code
        }, 400);
      }

      const [{ data: existingExpensesLink }, { data: existingReportsLink }] = await Promise.all([
        admin
          .from("telegram_links")
          .select("chat_id, bot_code, label")
          .eq("user_id", userId)
          .in("bot_code", codeCandidates)
          .maybeSingle(),
        admin
          .from("telegram_reports_links")
          .select("chat_id, bot_code, label")
          .eq("user_id", userId)
          .in("bot_code", codeCandidates)
          .maybeSingle(),
      ]);

      if (existingExpensesLink || existingReportsLink) {
        const link = existingReportsLink ?? existingExpensesLink;
        return json({
          ok: true,
          already_linked: true,
          kind: existingReportsLink ? "reports" : "expenses",
          chat_id: Number((link as any).chat_id),
          bot_code: (link as any).bot_code,
          label: (link as any).label ?? null,
          message: "Este código já foi consumido e o bot já está vinculado.",
        });
      }

      console.log("Código não encontrado em nenhuma tabela de vínculo:", { code, codeCandidates });
      return json({
        ok: false,
        error: "Código não encontrado neste app. Envie /code novamente no Telegram, aguarde a resposta do bot e cole o código mais recente recebido.",
      });
    }


    if ((bot as any).expires_at && new Date((bot as any).expires_at).getTime() < Date.now()) {
      return json({ error: "Código expirado. Gere um novo no bot enviando /code." }, 410);
    }

    const consumedCode = String((bot as any).bot_code);
    const kind = (bot as any).kind as "expenses" | "reports";
    const chatId = Number((bot as any).chat_id);

    const targetTable = kind === "reports" ? "telegram_reports_links" : "telegram_links";
    const rawLabel = typeof body?.label === "string" ? body.label.trim().slice(0, 80) : "";
    const label = rawLabel || null;

    // Múltiplos vínculos paralelos: chave = (user_id, chat_id).
    // Se já existir, atualiza bot_code/label preservando dados; senão cria novo
    // sem remover outros vínculos existentes do mesmo usuário.
    const { error: upsertErr } = await admin
      .from(targetTable)
      .upsert(
        { user_id: userId, chat_id: chatId, bot_id: (bot as any).bot_id ?? null, bot_code: consumedCode, label },
        { onConflict: "user_id,chat_id" },
      );

    if (upsertErr) return json({ error: upsertErr.message }, 500);

    // One-shot: invalida o código consumido (o vínculo persiste em telegram_*_links
    // e pode ser reutilizado por outros relatórios sem refazer o pareamento).
    await admin.from("telegram_bots").delete().eq("id", (bot as any).id);

    return json({
      ok: true,
      kind,
      chat_id: chatId,
      bot_code: consumedCode,
      label,
      message: "Bot vinculado com sucesso. O código foi consumido, mas o vínculo permanece salvo.",
    });
  } catch (e: any) {
    return json({ error: e?.message ?? "Erro interno" }, 500);
  }
});
